services:
  - type: web
    name: poly-alpha-landing
    runtime: static
    staticPublishPath: ./landing-page
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
