"""Deterministic, fully offline research engine over market snapshots.

No network and no model calls are made: every estimate is a pure function of the
snapshot, derived from the de-vigged market price, order-book depth, and liquidity.
Uncertainty intervals widen as data quality falls so consumers can size confidence
honestly.
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import UTC, datetime

from poly_alpha.contracts import (
    DataSourceKind,
    MarketSnapshot,
    PriceLevel,
    Provenance,
    Uncertainty,
)
from poly_alpha.research.notes import ResearchClaim, ResearchNote
from poly_alpha.strategy import classify_category, shin_debiasing

_FIXED_TIME = datetime(1970, 1, 1, tzinfo=UTC)
_LIQUIDITY_REFERENCE = 500.0
_DEPTH_REFERENCE = 100.0
_IMBALANCE_WEIGHT = 0.15
_MAX_BOOK_LEVELS = 3
_BASE_HALF_WIDTH = 0.04
_LIQUIDITY_HALF_WIDTH = 0.18
_DEPTH_HALF_WIDTH = 0.12
_MAX_HALF_WIDTH = 0.5
_NEUTRAL_DEADBAND = 0.005


def _clamp(value: float, low: float = 0.0, high: float = 1.0) -> float:
    return max(low, min(high, value))


def _sign_direction(value: float) -> str:
    if value > _NEUTRAL_DEADBAND:
        return "bullish_yes"
    if value < -_NEUTRAL_DEADBAND:
        return "bearish_yes"
    return "neutral"


def _direction(probability: float) -> str:
    return _sign_direction(probability - 0.5)


def _best_levels(orderbook: tuple[PriceLevel, ...]) -> tuple[PriceLevel, ...]:
    return orderbook[:_MAX_BOOK_LEVELS]


def _orderbook_depth(orderbook: tuple[PriceLevel, ...]) -> float:
    return sum(level.size for level in _best_levels(orderbook))


def _orderbook_imbalance(orderbook: tuple[PriceLevel, ...]) -> float:
    levels = _best_levels(orderbook)
    yes_pressure = sum(level.price * level.size for level in levels)
    no_pressure = sum((1.0 - level.price) * level.size for level in levels)
    total = yes_pressure + no_pressure
    if total <= 0.0:
        return 0.0
    return (yes_pressure - no_pressure) / total


def _heuristic_source(snapshot: MarketSnapshot) -> Provenance:
    return Provenance(
        source="poly_alpha.research.analyst",
        kind=DataSourceKind.SIMULATED,
        retrieved_at=snapshot.provenance.retrieved_at,
        note="Deterministic heuristic adjustment generated by the research engine.",
    )


def _resolve_time(snapshot: MarketSnapshot, now: datetime | None) -> datetime:
    if now is not None:
        return now
    if snapshot.provenance.retrieved_at is not None:
        return snapshot.provenance.retrieved_at
    return _FIXED_TIME


def _build_claims(
    snapshot: MarketSnapshot,
    implied: float | None,
    estimate: float,
    edge_center: float,
    method: str,
    imbalance: float,
    depth: float,
    liquidity_confidence: float,
    book_confidence: float,
    heuristic_used: bool,
) -> tuple[ResearchClaim, ...]:
    snapshot_source = snapshot.provenance
    heuristic = _heuristic_source(snapshot)
    method_sources = (snapshot_source, heuristic) if heuristic_used else (snapshot_source,)

    claims: list[ResearchClaim] = []
    if implied is not None:
        market_text = (
            f"De-vigged market implies {implied:.1%} YES from listed "
            f"YES/NO prices {snapshot.yes_price:.3f}/{snapshot.no_price:.3f}."
        )
        claims.append(
            ResearchClaim(market_text, _direction(implied), liquidity_confidence, (snapshot_source,))
        )
    else:
        claims.append(
            ResearchClaim(
                "No two-sided price is available; a neutral 0.5 prior is used.",
                "neutral",
                _clamp(1.0 - liquidity_confidence),
                (snapshot_source,),
            )
        )

    if snapshot.orderbook:
        method_text = (
            f"Best {len(_best_levels(snapshot.orderbook))} order-book levels are "
            f"{imbalance:+.1%} depth-weighted toward YES; book depth {depth:.1f}."
        )
        claims.append(
            ResearchClaim(method_text, _sign_direction(imbalance), book_confidence, method_sources)
        )
    elif implied is not None:
        method_text = (
            "No order book is available; Shin (1992) debiasing is applied to the "
            "de-vigged YES price."
        )
        claims.append(
            ResearchClaim(method_text, _direction(estimate), liquidity_confidence, method_sources)
        )
    else:
