"""Deterministic, fully offline research engine over market snapshots.

No network and no model calls are made: every estimate is a pure function of the
snapshot, derived from the de-vigged market price, order-book depth, and liquidity.
Uncertainty intervals widen as data quality falls so consumers can size confidence
honestly.
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import UTC, datetime

from poly_alpha.contracts import (
    DataSourceKind,
    MarketSnapshot,
    PriceLevel,
    Provenance,
    Uncertainty,
)
from poly_alpha.research.notes import ResearchClaim, ResearchNote
from poly_alpha.strategy import classify_category, shin_debiasing

_FIXED_TIME = datetime(1970, 1, 1, tzinfo=UTC)
_LIQUIDITY_REFERENCE = 500.0
_DEPTH_REFERENCE = 100.0
_IMBALANCE_WEIGHT = 0.15
_MAX_BOOK_LEVELS = 3
_BASE_HALF_WIDTH = 0.04
_LIQUIDITY_HALF_WIDTH = 0.18
_DEPTH_HALF_WIDTH = 0.12
_MAX_HALF_WIDTH = 0.5
_NEUTRAL_DEADBAND = 0.005


def _clamp(value: float, low: float = 0.0, high: float = 1.0) -> float:
    return max(low, min(high, value))


def _sign_direction(value: float) -> str:
    if value > _NEUTRAL_DEADBAND:
        return "bullish_yes"
    if value < -_NEUTRAL_DEADBAND:
        return "bearish_yes"
    return "neutral"


def _direction(probability: float) -> str:
    return _sign_direction(probability - 0.5)


def _best_levels(orderbook: tuple[PriceLevel, ...]) -> tuple[PriceLevel, ...]:
    return orderbook[:_MAX_BOOK_LEVELS]


def _orderbook_depth(orderbook: tuple[PriceLevel, ...]) -> float:
    return sum(level.size for level in _best_levels(orderbook))


def _orderbook_imbalance(orderbook: tuple[PriceLevel, ...]) -> float:
    levels = _best_levels(orderbook)
    yes_pressure = sum(level.price * level.size for level in levels)
    no_pressure = sum((1.0 - level.price) * level.size for level in levels)
    total = yes_pressure + no_pressure
    if total <= 0.0:
        return 0.0
    return (yes_pressure - no_pressure) / total


def _heuristic_source(snapshot: MarketSnapshot) -> Provenance:
    return Provenance(
        source="poly_alpha.research.analyst",
        kind=DataSourceKind.SIMULATED,
        retrieved_at=snapshot.provenance.retrieved_at,
        note="Deterministic heuristic adjustment generated by the research engine.",
    )


def _resolve_time(snapshot: MarketSnapshot, now: datetime | None) -> datetime:
    if now is not None:
        return now
    if snapshot.provenance.retrieved_at is not None:
        return snapshot.provenance.retrieved_at
    return _FIXED_TIME


def _build_claims(
    snapshot: MarketSnapshot,
    implied: float | None,
    estimate: float,
    edge_center: float,
    method: str,
    imbalance: float,
    depth: float,
    liquidity_confidence: float,
    book_confidence: float,
    heuristic_used: bool,
) -> tuple[ResearchClaim, ...]:
    snapshot_source = snapshot.provenance
    heuristic = _heuristic_source(snapshot)
    method_sources = (snapshot_source, heuristic) if heuristic_used else (snapshot_source,)

    claims: list[ResearchClaim] = []
    if implied is not None:
        market_text = (
            f"De-vigged market implies {implied:.1%} YES from listed "
            f"YES/NO prices {snapshot.yes_price:.3f}/{snapshot.no_price:.3f}."
        )
        claims.append(
            ResearchClaim(
                market_text,
                _direction(implied),
                liquidity_confidence,
                (snapshot_source,),
            )
        )
    else:
        claims.append(
            ResearchClaim(
                "No two-sided price is available; a neutral 0.5 prior is used.",
                "neutral",
                _clamp(1.0 - liquidity_confidence),
                (snapshot_source,),
            )
        )

    if snapshot.orderbook:
        method_text = (
            f"Best {len(_best_levels(snapshot.orderbook))} order-book levels are "
            f"{imbalance:+.1%} depth-weighted toward YES; book depth {depth:.1f}."
        )
        claims.append(
            ResearchClaim(method_text, _sign_direction(imbalance), book_confidence, method_sources)
        )
    elif implied is not None:
        method_text = (
            "No order book is available; Shin (1992) debiasing is applied to the "
            "de-vigged YES price."
        )
        claims.append(
            ResearchClaim(method_text, _direction(estimate), liquidity_confidence, method_sources)
        )
    else:
        claims.append(
            ResearchClaim(
                "No order book or market price is available; the neutral prior is retained.",
                "neutral",
                liquidity_confidence,
                method_sources,
            )
        )

    model_text = (
        f"Model YES estimate is {estimate:.1%} against a {edge_center:.1%} reference "
        f"(edge {estimate - edge_center:+.1%}) via {method}."
    )
    claims.append(
        ResearchClaim(
            model_text,
            _direction(estimate),
            _clamp(0.5 + 0.5 * liquidity_confidence),
            method_sources,
        )
    )

    liquidity_text = (
        f"Liquidity of {snapshot.liquidity:.1f} yields {liquidity_confidence:.0%} "
        "confidence; the estimate is shrunk toward 0.5 accordingly."
    )
    claims.append(
        ResearchClaim(
            liquidity_text,
            _direction(estimate),
            _clamp(1.0 - liquidity_confidence),
            method_sources,
        )
    )
    return tuple(claims)


def research_market(snapshot: MarketSnapshot, *, now: datetime | None = None) -> ResearchNote:
    """Build a deterministic, provenance-tagged research note for one snapshot."""
    implied = snapshot.implied_yes()
    orderbook = snapshot.orderbook
    has_book = bool(orderbook)

    liquidity_confidence = _clamp(snapshot.liquidity / _LIQUIDITY_REFERENCE)
    depth = _orderbook_depth(orderbook)
    book_confidence = _clamp(depth / _DEPTH_REFERENCE)
    imbalance = _orderbook_imbalance(orderbook)

    base = implied if implied is not None else 0.5
    if has_book:
        method = "devig+orderbook-imbalance"
        base = _clamp(base + _IMBALANCE_WEIGHT * imbalance)
    elif implied is not None:
        method = "shin-debias"
        base = shin_debiasing(implied, classify_category(snapshot.question))
    else:
        method = "neutral-prior"

    estimate = _clamp(0.5 + liquidity_confidence * (base - 0.5))
    half_width = _clamp(
        _BASE_HALF_WIDTH
        + _LIQUIDITY_HALF_WIDTH * (1.0 - liquidity_confidence)
        + _DEPTH_HALF_WIDTH * (1.0 - book_confidence),
        high=_MAX_HALF_WIDTH,
    )
    low = _clamp(estimate - half_width)
    high = _clamp(estimate + half_width)
    basis = f"{method}+liquidity-shrink (simulated heuristic)"

    model_yes = Uncertainty(
        estimate=estimate,
        low=low,
        high=high,
        basis=basis,
        n_observations=len(orderbook),
        simulated=True,
    )

    if implied is not None:
        edge_center = implied
        edge_basis = "model estimate minus de-vigged market implied"
    else:
        edge_center = 0.5
        edge_basis = "model estimate minus neutral 0.5 prior (no market price)"
    edge = Uncertainty(
        estimate=estimate - edge_center,
        low=low - edge_center,
        high=high - edge_center,
        basis=edge_basis,
        n_observations=0,
        simulated=True,
    )

    heuristic_used = has_book or implied is not None
    claims = _build_claims(
        snapshot,
        implied,
        estimate,
        edge_center,
        method,
        imbalance,
        depth,
        liquidity_confidence,
        book_confidence,
        heuristic_used,
    )

    if snapshot.provenance.kind is DataSourceKind.REAL:
        data_caveat = (
            f"Market data is real observed data from {snapshot.provenance.source}."
        )
    else:
        data_caveat = (
            f"Market data is {snapshot.provenance.kind.value} "
            f"({snapshot.provenance.source}) and is not a real observation."
        )
    caveats = (
        data_caveat,
        "This is research and paper-trading output only, not investment advice.",
        "The model estimate is a simulated heuristic and is not a calibrated forecast.",
    )
    if not has_book:
        caveats = caveats + ("No order book was available, so the interval is widened.",)

    market_part = f"{implied:.1%}" if implied is not None else "n/a"
    summary = (
        f"{snapshot.question} | model {estimate:.1%} YES vs market {market_part}, "
        f"edge {estimate - edge_center:+.1%} | {method}"
    )

    return ResearchNote(
        market_id=snapshot.market_id,
        question=snapshot.question,
        summary=summary,
        claims=claims,
        market_implied_yes=implied,
        model_yes=model_yes,
        edge=edge,
        provenance=snapshot.provenance,
        generated_at=_resolve_time(snapshot, now),
        caveats=caveats,
    )


def research_markets(
    snapshots: Sequence[MarketSnapshot], *, now: datetime | None = None
) -> list[ResearchNote]:
    """Build research notes for many snapshots, preserving input order."""
    return [research_market(snapshot, now=now) for snapshot in snapshots]


def model_vs_market(note: ResearchNote) -> float | None:
    """Signed edge (model estimate minus market implied), or None without a market price."""
    if note.market_implied_yes is None:
        return None
    return note.model_yes.estimate - note.market_implied_yes
